### ISSUE TITLE
close() not implemented

### ISSUE THREAD

**Issue by gjim83** [mzbroch/napalm-f5#1]
I suppose this repo is early stage but it's already proven a bit useful to my project at $current_employer!
However, the lack of a `close()` method is causing an harmless yet annoying `NotImplementedError` exception.
I'm not familiar with the `bigsuds` library so I couldn't suggest the best implementation of the method through a PR, but I implemented a simple `pass` locally, and _for my use cases_ it works.

Before patching:
```python
>>> with dr('XXXX', 'YYYYYY', 'ZZZZZZZ') as dev:
...   facts = dev.get_facts()
...   ifs = dev.get_interfaces()
...   l3_ifs = dev.get_interfaces_ip()
...
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Users/Guido_Jimenez/abc/.virtualenvs/myenv/lib/python3.5/site-packages/napalm_base/base.py", line 51, in __exit__
    self.close()
  File "/Users/Guido_Jimenez/abc/.virtualenvs/myenv/lib/python3.5/site-packages/napalm_base/base.py", line 83, in close
    raise NotImplementedError
NotImplementedError
```

**Comment by mzbroch** [comment]
Thanks for your interest in this module - let me analyze what would be the best way to implement close() method and I'll get back to you soon with an update on this issue.

**Comment by gjim83** [comment]
no worries. hope you don't mind if I fork this internally? I can provide feedback/further PR's as I find anything worth noting
